/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.util.List;
import java.util.ArrayList;
import java.sql.Timestamp;



/**
 *
 * @author HP
 */
public class AdminMenu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminMenu.class.getName());

    /**
     * Creates new form AdminMenu
     */
    public AdminMenu() {
        initComponents();
        getContentPane().setBackground(new Color(255, 182, 193)); // Light pink

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jLabelAdminDashboard = new javax.swing.JLabel();
        jButtonViewAllProducts = new javax.swing.JButton();
        jButtonAddCategory = new javax.swing.JButton();
        jButtonViewAllOrders = new javax.swing.JButton();
        jButtonViewStaffAndCustomers = new javax.swing.JButton();
        jButtonViewPayments = new javax.swing.JButton();
        jButtonLogout = new javax.swing.JButton();
        jButtonGenerateAnalytics = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuUsers = new javax.swing.JMenu();
        jMenuUsersReport = new javax.swing.JMenu();
        jMenuItemUsersReportMenu = new javax.swing.JMenuItem();
        jMenuAnalytics = new javax.swing.JMenu();
        jMenuItemSalesReport = new javax.swing.JMenuItem();
        jMenuItemInventoryTrends = new javax.swing.JMenuItem();
        jMenuAccount = new javax.swing.JMenu();
        jMenuItemLogout = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        jMenu4.setText("jMenu4");

        jMenuItem3.setText("jMenuItem3");

        jMenuItem4.setText("jMenuItem4");

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelAdminDashboard.setText("   Admin Dashboard");

        jButtonViewAllProducts.setText("View All Products");
        jButtonViewAllProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewAllProductsActionPerformed(evt);
            }
        });

        jButtonAddCategory.setText("Add Category");
        jButtonAddCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddCategoryActionPerformed(evt);
            }
        });

        jButtonViewAllOrders.setText("View All Orders");
        jButtonViewAllOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewAllOrdersActionPerformed(evt);
            }
        });

        jButtonViewStaffAndCustomers.setText("View Staff & Customers");
        jButtonViewStaffAndCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewStaffAndCustomersActionPerformed(evt);
            }
        });

        jButtonViewPayments.setText("View Payments");
        jButtonViewPayments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewPaymentsActionPerformed(evt);
            }
        });

        jButtonLogout.setText("Logout");
        jButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogoutActionPerformed(evt);
            }
        });

        jButtonGenerateAnalytics.setText("Generate Analytics");
        jButtonGenerateAnalytics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenerateAnalyticsActionPerformed(evt);
            }
        });

        jMenuUsers.setText("Users");

        jMenuUsersReport.setText("Users Overview");

        jMenuItemUsersReportMenu.setText("Users Report");
        jMenuItemUsersReportMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUsersReportMenuActionPerformed(evt);
            }
        });
        jMenuUsersReport.add(jMenuItemUsersReportMenu);

        jMenuUsers.add(jMenuUsersReport);

        jMenuBar1.add(jMenuUsers);

        jMenuAnalytics.setText("Analytics");

        jMenuItemSalesReport.setText("Sales Reports");
        jMenuAnalytics.add(jMenuItemSalesReport);

        jMenuItemInventoryTrends.setText("Inventory Trends");
        jMenuItemInventoryTrends.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemInventoryTrendsActionPerformed(evt);
            }
        });
        jMenuAnalytics.add(jMenuItemInventoryTrends);

        jMenuBar1.add(jMenuAnalytics);

        jMenuAccount.setText("Account");

        jMenuItemLogout.setText("Logout");
        jMenuItemLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLogoutActionPerformed(evt);
            }
        });
        jMenuAccount.add(jMenuItemLogout);

        jMenuBar1.add(jMenuAccount);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(jLabelAdminDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonGenerateAnalytics, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonViewAllProducts, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonViewStaffAndCustomers, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButtonViewPayments, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addComponent(jButtonViewAllOrders, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAddCategory, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(17, 17, 17))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabelAdminDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonViewAllProducts)
                    .addComponent(jButtonAddCategory))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonViewAllOrders)
                    .addComponent(jButtonViewStaffAndCustomers))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonViewPayments)
                    .addComponent(jButtonGenerateAnalytics))
                .addGap(95, 95, 95)
                .addComponent(jButtonLogout)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed
        // TODO add your handling code here:
        Login login = new Login();
    login.setVisible(true);
    this.dispose(); // close the dashboard

    }//GEN-LAST:event_jButtonLogoutActionPerformed

    private void jMenuItemLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLogoutActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jMenuItemLogoutActionPerformed

    private void jButtonViewAllProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewAllProductsActionPerformed
        // TODO add your handling code here:
        jButtonViewAllProducts.addActionListener(e -> {
    try {
        List<String> products = fetchAllProducts();
        StringBuilder message = new StringBuilder("All Products:\n\n");
        for (String product : products) {
            message.append(product).append("\n----------------------\n");
        }
        JOptionPane.showMessageDialog(null, message.toString(), "Product List", JOptionPane.INFORMATION_MESSAGE);
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(null, "Error loading products: " + ex.getMessage());
    }
});

    }//GEN-LAST:event_jButtonViewAllProductsActionPerformed

    private void jButtonViewStaffAndCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewStaffAndCustomersActionPerformed
        // TODO add your handling code here:
        jButtonViewStaffAndCustomers.addActionListener(e -> {
    try {
        List<String> users = fetchStaffAndCustomers();
        StringBuilder message = new StringBuilder("Staff & Customers:\n\n");
        for (String user : users) {
            message.append(user).append("\n----------------------\n");
        }
        JOptionPane.showMessageDialog(null, message.toString(), "User Roles", JOptionPane.INFORMATION_MESSAGE);
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(null, "Error loading users: " + ex.getMessage());
    }
});

    }//GEN-LAST:event_jButtonViewStaffAndCustomersActionPerformed

    private void jButtonViewAllOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewAllOrdersActionPerformed
        // TODO add your handling code here:
        jButtonViewAllOrders.addActionListener(e -> {
    try {
        List<String> orders = fetchAllOrders();
        StringBuilder message = new StringBuilder("All Orders:\n\n");
        for (String order : orders) {
            message.append(order).append("\n----------------------\n");
        }
        JOptionPane.showMessageDialog(null, message.toString(), "Orders Overview", JOptionPane.INFORMATION_MESSAGE);
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(null, "Error loading orders: " + ex.getMessage());
    }
});

    }//GEN-LAST:event_jButtonViewAllOrdersActionPerformed

    private void jButtonViewPaymentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewPaymentsActionPerformed
        // TODO add your handling code here:
        jButtonViewPayments.addActionListener(e -> {
    try {
        List<String> payments = fetchAllPayments();
        StringBuilder message = new StringBuilder("All Payments:\n\n");
        for (String payment : payments) {
            message.append(payment).append("\n----------------------\n");
        }
        JOptionPane.showMessageDialog(null, message.toString(), "Payments Overview", JOptionPane.INFORMATION_MESSAGE);
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(null, "Error loading payments: " + ex.getMessage());
    }
});

    }//GEN-LAST:event_jButtonViewPaymentsActionPerformed

    private void jMenuItemUsersReportMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUsersReportMenuActionPerformed
        // TODO add your handling code here:
        reports.generateReportWithChooser("admin");
    }//GEN-LAST:event_jMenuItemUsersReportMenuActionPerformed

    private void jButtonAddCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddCategoryActionPerformed
        // TODO add your handling code here:
        jButtonAddCategory.addActionListener(e -> {
    try {
        String categoryName = JOptionPane.showInputDialog(null, "Enter new category name:");
        if (categoryName != null && !categoryName.trim().isEmpty()) {
            boolean success = insertNewCategory(categoryName.trim());
            if (success) {
                JOptionPane.showMessageDialog(null, "Category added successfully.");
            } else {
                JOptionPane.showMessageDialog(null, "Failed to add category.");
            }
        }
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
    }
});

    }//GEN-LAST:event_jButtonAddCategoryActionPerformed

    private void jButtonGenerateAnalyticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenerateAnalyticsActionPerformed
        // TODO add your handling code here:
        jButtonGenerateAnalytics.addActionListener(e -> {
    try {
        String report = generateAnalyticsReport();
        JOptionPane.showMessageDialog(null, report, "Analytics Summary", JOptionPane.INFORMATION_MESSAGE);
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(null, "Error generating analytics: " + ex.getMessage());
    }
});

    }//GEN-LAST:event_jButtonGenerateAnalyticsActionPerformed

    private void jMenuItemInventoryTrendsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemInventoryTrendsActionPerformed
        // TODO add your handling code here:
        jMenuItemInventoryTrends.addActionListener(e -> {
    try {
        String report = generateInventoryTrends();
        JOptionPane.showMessageDialog(null, report, "Inventory Trends", JOptionPane.INFORMATION_MESSAGE);
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(null, "Error generating inventory trends: " + ex.getMessage());
    }
});

    }//GEN-LAST:event_jMenuItemInventoryTrendsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdminMenu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddCategory;
    private javax.swing.JButton jButtonGenerateAnalytics;
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JButton jButtonViewAllOrders;
    private javax.swing.JButton jButtonViewAllProducts;
    private javax.swing.JButton jButtonViewPayments;
    private javax.swing.JButton jButtonViewStaffAndCustomers;
    private javax.swing.JLabel jLabelAdminDashboard;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenuAccount;
    private javax.swing.JMenu jMenuAnalytics;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItemInventoryTrends;
    private javax.swing.JMenuItem jMenuItemLogout;
    private javax.swing.JMenuItem jMenuItemSalesReport;
    private javax.swing.JMenuItem jMenuItemUsersReportMenu;
    private javax.swing.JMenu jMenuUsers;
    private javax.swing.JMenu jMenuUsersReport;
    // End of variables declaration//GEN-END:variables

private List<String> fetchAllProducts() throws SQLException {
    List<String> products = new ArrayList<>();
    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/ecommercesystem", "root", "");
    String query = "SELECT product_id, name, description, price, last_updated FROM products ORDER BY product_id ASC";
    PreparedStatement ps = conn.prepareStatement(query);
    ResultSet rs = ps.executeQuery();
    while (rs.next()) {
        String product = "Product ID: " + rs.getInt("product_id") +
                         "\nName: " + rs.getString("name") +
                         "\nDescription: " + rs.getString("description") +
                         "\nPrice: $" + rs.getDouble("price") +
                         "\nLast Updated: " + rs.getTimestamp("last_updated");
        products.add(product);
    }
    conn.close();
    return products;
}

private List<String> fetchStaffAndCustomers() throws SQLException {
    List<String> users = new ArrayList<>();
    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/ecommercesystem", "root", "");
    String query = "SELECT user_id, full_name, email, phone, role FROM users WHERE role IN ('staff', 'customer') ORDER BY role, user_id ASC";
    PreparedStatement ps = conn.prepareStatement(query);
    ResultSet rs = ps.executeQuery();
    while (rs.next()) {
        String user = "User ID: " + rs.getString("user_id") +
                      "\nName: " + rs.getString("full_name") +
                      "\nEmail: " + rs.getString("email") +
                      "\nPhone: " + rs.getString("phone") +
                      "\nRole: " + rs.getString("role");
        users.add(user);
    }
    conn.close();
    return users;
}
 
private List<String> fetchAllOrders() throws SQLException {
    List<String> orders = new ArrayList<>();
    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/ecommercesystem", "root", "");
    String query = "SELECT order_id, user_id, order_date, status FROM orders ORDER BY order_date DESC";
    PreparedStatement ps = conn.prepareStatement(query);
    ResultSet rs = ps.executeQuery();
    while (rs.next()) {
        String order = "Order ID: " + rs.getInt("order_id") +
                       "\nUser ID: " + rs.getString("user_id") +
                       "\nDate: " + rs.getTimestamp("order_date") +
                       "\nStatus: " + rs.getString("status");
        orders.add(order);
    }
    conn.close();
    return orders;
}
private List<String> fetchAllPayments() throws SQLException {
    List<String> payments = new ArrayList<>();
    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/ecommercesystem", "root", "");
    String query = "SELECT payment_id, order_id, payment_date, method, status FROM payments ORDER BY payment_date DESC";
    PreparedStatement ps = conn.prepareStatement(query);
    ResultSet rs = ps.executeQuery();
    while (rs.next()) {
        String payment = "Payment ID: " + rs.getInt("payment_id") +
                         "\nOrder ID: " + rs.getInt("order_id") +
                         "\nDate: " + rs.getTimestamp("payment_date") +
                         "\nMethod: " + rs.getString("method") +
                         "\nStatus: " + rs.getString("status");
        payments.add(payment);
    }
    conn.close();
    return payments;
}
private boolean insertNewCategory(String name) throws SQLException {
    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/ecommercesystem", "root", "");
    String query = "INSERT INTO categories (name) VALUES (?)";
    PreparedStatement ps = conn.prepareStatement(query);
    ps.setString(1, name);
    int rows = ps.executeUpdate();
    conn.close();
    return rows > 0;
}
private String generateAnalyticsReport() throws SQLException {
    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/ecommercesystem", "root", "");

    StringBuilder report = new StringBuilder("📊 Analytics Summary:\n\n");

    // Total Orders
    PreparedStatement ps1 = conn.prepareStatement("SELECT COUNT(*) FROM orders");
    ResultSet rs1 = ps1.executeQuery();
    if (rs1.next()) {
        report.append("Total Orders: ").append(rs1.getInt(1)).append("\n");
    }

    // Total Revenue
    PreparedStatement ps2 = conn.prepareStatement("SELECT SUM(amount) FROM payments WHERE status = 'completed'");
    ResultSet rs2 = ps2.executeQuery();
    if (rs2.next()) {
        report.append("Total Revenue: $").append(rs2.getDouble(1)).append("\n");
    }

    // Payment Method Breakdown
    PreparedStatement ps3 = conn.prepareStatement(
        "SELECT method, COUNT(*) AS count FROM payments GROUP BY method"
    );
    ResultSet rs3 = ps3.executeQuery();
    report.append("\nPayment Method Breakdown:\n");
    while (rs3.next()) {
        report.append("- ").append(rs3.getString("method"))
              .append(": ").append(rs3.getInt("count")).append(" payments\n");
    }

    conn.close();
    return report.toString();
}
 
private String generateInventoryTrends() throws SQLException {
    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/ecommercesystem", "root", "");
    StringBuilder report = new StringBuilder("📦 Inventory Trends:\n\n");

    // Total products
    PreparedStatement ps1 = conn.prepareStatement("SELECT COUNT(*) FROM products");
    ResultSet rs1 = ps1.executeQuery();
    if (rs1.next()) {
        report.append("Total Products: ").append(rs1.getInt(1)).append("\n");
    }

    // Low stock alert (e.g. stock_quantity < 10)
    PreparedStatement ps2 = conn.prepareStatement(
        "SELECT name, stock_quantity FROM products WHERE stock_quantity < 10 ORDER BY stock_quantity ASC"
    );
    ResultSet rs2 = ps2.executeQuery();
    report.append("\n⚠️ Low Stock Products:\n");
    boolean hasLowStock = false;
    while (rs2.next()) {
        hasLowStock = true;
        report.append("- ").append(rs2.getString("name"))
              .append(": ").append(rs2.getInt("stock_quantity")).append(" units\n");
    }
    if (!hasLowStock) {
        report.append("None\n");
    }

    // Recently updated products
    PreparedStatement ps3 = conn.prepareStatement(
        "SELECT name, last_updated FROM products ORDER BY last_updated DESC LIMIT 5"
    );
    ResultSet rs3 = ps3.executeQuery();
    report.append("\n🕒 Recently Updated Products:\n");
    while (rs3.next()) {
        report.append("- ").append(rs3.getString("name"))
              .append(" (Updated: ").append(rs3.getTimestamp("last_updated")).append(")\n");
    }

    conn.close();
    return report.toString();
}

}
