
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.*;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import newpackagedb.DBConnection;
import javax.swing.JScrollPane;
import java.awt.Dimension;
import PaymentServices.PaymentMethods;
import java.util.List;
import java.util.ArrayList;
import java.sql.Timestamp;



    
    

  




/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author HP
 */
public class CustomerMenu extends javax.swing.JFrame {
    Connection con;
    Statement st;
    String dblink;
    PreparedStatement pst;
    
    String user_id;
    String user;
    String password;
    
    String query;
    ResultSet rs;
    private String currentUserId;

    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CustomerMenu.class.getName());

    /**
     * Creates new form CustomerMenu
     */
    public CustomerMenu(String userId) {
        
        con=null;
        st=null;
        dblink="jdbc:mysql://localhost:3306/ecommercesystem";
        user = "root";
        password = "";
        
        initComponents();
        this.currentUserId = userId;
        cartTable.setVisible(false); // hide the table initially

        getContentPane().setBackground(new Color(255, 182, 193)); // Light pink
         setTitle("Customer Dashboard");
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jLabelCustomerDashboard = new javax.swing.JLabel();
        btnSearchProducts = new javax.swing.JButton();
        jButtonPlaceOrder = new javax.swing.JButton();
        jButtonOrderHistory = new javax.swing.JButton();
        jButtonAddToCart = new javax.swing.JButton();
        jButtonViewCart = new javax.swing.JButton();
        jButtonMakePayments = new javax.swing.JButton();
        jButtonClearCart = new javax.swing.JButton();
        jButtonTrackShipping = new javax.swing.JButton();
        jButtonLogout = new javax.swing.JButton();
        ScrollPane = new javax.swing.JScrollPane();
        productTable = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        cartTable = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenushop = new javax.swing.JMenu();
        jMenuItemBrowseProducts = new javax.swing.JMenuItem();
        jMenuItemSearchbyCategory = new javax.swing.JMenuItem();
        jMenuOrders = new javax.swing.JMenu();
        jMenuItemMyOrders = new javax.swing.JMenuItem();
        jMenuItemTrackShipping = new javax.swing.JMenuItem();
        jMenuPayments = new javax.swing.JMenu();
        jMenuItemPaymentHistory = new javax.swing.JMenuItem();
        jMenuAccount = new javax.swing.JMenu();
        jMenuItemEditProfile = new javax.swing.JMenuItem();
        jMenuItemLogOut = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar2.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelCustomerDashboard.setText("Customer Dashboard");

        btnSearchProducts.setText("Search Products");
        btnSearchProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchProductsActionPerformed(evt);
            }
        });

        jButtonPlaceOrder.setText("Place Order");
        jButtonPlaceOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlaceOrderActionPerformed(evt);
            }
        });

        jButtonOrderHistory.setText("Order History");

        jButtonAddToCart.setText("Add to Cart");
        jButtonAddToCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddToCartActionPerformed(evt);
            }
        });

        jButtonViewCart.setText("View Cart");
        jButtonViewCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewCartActionPerformed(evt);
            }
        });

        jButtonMakePayments.setText("Make Payments");
        jButtonMakePayments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMakePaymentsActionPerformed(evt);
            }
        });

        jButtonClearCart.setText("Clear Cart");
        jButtonClearCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearCartActionPerformed(evt);
            }
        });

        jButtonTrackShipping.setText("Track Shipping");
        jButtonTrackShipping.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTrackShippingActionPerformed(evt);
            }
        });

        jButtonLogout.setText("Logout");
        jButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogoutActionPerformed(evt);
            }
        });

        productTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Product ID", "Name", "Price", "Stock"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        ScrollPane.setViewportView(productTable);

        cartTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Product ID", "Name", "Price", "Quantity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        cartTable.setEnabled(false);
        jScrollPane1.setViewportView(cartTable);

        jMenushop.setText("Shop");

        jMenuItemBrowseProducts.setText("Browse Products");
        jMenushop.add(jMenuItemBrowseProducts);

        jMenuItemSearchbyCategory.setText("Search by Category");
        jMenushop.add(jMenuItemSearchbyCategory);

        jMenuBar1.add(jMenushop);

        jMenuOrders.setText("Orders");

        jMenuItemMyOrders.setText("My Orders");
        jMenuItemMyOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMyOrdersActionPerformed(evt);
            }
        });
        jMenuOrders.add(jMenuItemMyOrders);

        jMenuItemTrackShipping.setText("Track Shipping");
        jMenuItemTrackShipping.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTrackShippingActionPerformed(evt);
            }
        });
        jMenuOrders.add(jMenuItemTrackShipping);

        jMenuBar1.add(jMenuOrders);

        jMenuPayments.setText("Payments");

        jMenuItemPaymentHistory.setText("Payment History");
        jMenuItemPaymentHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPaymentHistoryActionPerformed(evt);
            }
        });
        jMenuPayments.add(jMenuItemPaymentHistory);

        jMenuBar1.add(jMenuPayments);

        jMenuAccount.setText("Account");

        jMenuItemEditProfile.setText("Edit Profile");
        jMenuAccount.add(jMenuItemEditProfile);

        jMenuItemLogOut.setText("LogOut");
        jMenuItemLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLogOutActionPerformed(evt);
            }
        });
        jMenuAccount.add(jMenuItemLogOut);

        jMenuBar1.add(jMenuAccount);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(jLabelCustomerDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
                    .addComponent(btnSearchProducts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 231, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonViewCart, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonAddToCart, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonPlaceOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(385, 385, 385))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonOrderHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButtonMakePayments)
                                .addComponent(jButtonTrackShipping, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButtonClearCart, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabelCustomerDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonLogout)
                            .addComponent(jButtonOrderHistory))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSearchProducts)
                            .addComponent(jButtonViewCart))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jButtonAddToCart)
                                .addGap(33, 33, 33)
                                .addComponent(jButtonPlaceOrder)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonClearCart)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jButtonTrackShipping)
                                .addGap(32, 32, 32)
                                .addComponent(jButtonMakePayments)))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPlaceOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlaceOrderActionPerformed
        // TODO add your handling code here:
       
    DefaultTableModel model = (DefaultTableModel) cartTable.getModel();
    int rowCount = model.getRowCount();

    if (rowCount == 0) {
        JOptionPane.showMessageDialog(this, "Cart is empty.");
        return;
    }

    try (Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/ecommercesystem", "root", "")) {

        for (int i = 0; i < rowCount; i++) {
            int productId = Integer.parseInt(model.getValueAt(i, 0).toString());
            String name = model.getValueAt(i, 1).toString();
            int quantity = Integer.parseInt(model.getValueAt(i, 3).toString());

            int stock = getStock(conn, productId);
            if (stock < quantity) {
                JOptionPane.showMessageDialog(this, "Insufficient stock for: " + name);
                return;
            }
        }

        for (int i = 0; i < rowCount; i++) {
            int productId = Integer.parseInt(model.getValueAt(i, 0).toString());
            int quantity = Integer.parseInt(model.getValueAt(i, 3).toString());

            int stock = getStock(conn, productId);
            int newStock = stock - quantity;

            updateStock(conn, productId, newStock);
        }

        insertOrder(conn, currentUserId); // Logs the order in your orders table
        model.setRowCount(0); // Clears the cart table
        JOptionPane.showMessageDialog(this, "Order placed successfully!");

    } catch (Exception ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error placing order.");
    }




   
    }//GEN-LAST:event_jButtonPlaceOrderActionPerformed

    private void btnSearchProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchProductsActionPerformed
        // TODO add your handling code here:
    
    // Create a table model with updated columns
    DefaultTableModel model = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false; // Prevent editing
        }
    };
    model.setColumnIdentifiers(new String[] {
        "Product ID", "Name", "Description", "Price", "Stock", "Last Updated", "Supplier ID"
    });

    try {
        Connection con = DBConnection.getConnection();
        String query = "SELECT product_id, name, description, price, stock_quantity, last_updated, supplier_id FROM products";
        PreparedStatement pst = con.prepareStatement(query);
        ResultSet rs = pst.executeQuery();

        while (rs.next()) {
            int id = rs.getInt("product_id");
            String name = rs.getString("name");
            String desc = rs.getString("description");
            double price = rs.getDouble("price");
            int stock = rs.getInt("stock_quantity");
            Timestamp updated = rs.getTimestamp("last_updated");
            int supplier = rs.getInt("supplier_id");

            model.addRow(new Object[] { id, name, desc, price, stock, updated, supplier });
        }

        productTable.setModel(model);
        productTable.setRowHeight(25);
        productTable.getTableHeader().setFont(new java.awt.Font("SansSerif", java.awt.Font.BOLD, 14));
        productTable.setFont(new java.awt.Font("SansSerif", java.awt.Font.PLAIN, 13));

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error loading products.");
    }


    

    }//GEN-LAST:event_btnSearchProductsActionPerformed

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed
        // TODO add your handling code here:
        
    Login login = new Login();
    login.setVisible(true);
    this.dispose(); // close the dashboard


    }//GEN-LAST:event_jButtonLogoutActionPerformed

    private void jButtonAddToCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddToCartActionPerformed
                                                    
    int selectedRow = productTable.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(null, "Please select a product to add.");
        return;
    }

    String productId = productTable.getValueAt(selectedRow, 0).toString();
    int quantity = 1;

    System.out.println("Current user ID: " + currentUserId);

    if (currentUserId == null || currentUserId.isEmpty()) {
        JOptionPane.showMessageDialog(null, "User ID is missing. Please log in again.");
        return;
    }

    try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con = DriverManager.getConnection(dblink, user, password);
        String sql = "INSERT INTO cart (user_id, product_id, quantity) VALUES (?, ?, ?)";
        PreparedStatement pst = con.prepareStatement(sql);
        pst.setString(1, currentUserId);
        pst.setString(2, productId);
        pst.setInt(3, quantity);

        int rowsInserted = pst.executeUpdate();
        if (rowsInserted > 0) {
            JOptionPane.showMessageDialog(null, "Product added to cart!");
        }

        pst.close();
        con.close();
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error adding product to cart.");
    }




    


    }//GEN-LAST:event_jButtonAddToCartActionPerformed

    private void jButtonViewCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewCartActionPerformed
        // TODO add your handling code here:
        cartTable.setVisible(true); // show the table when clicked
loadCartItems(); // load the cart data

        
    }//GEN-LAST:event_jButtonViewCartActionPerformed

    private void jButtonMakePaymentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMakePaymentsActionPerformed
        // TODO add your handling code here:
         // Step 1: Ask for phone number
    String phone = JOptionPane.showInputDialog(this, "Enter your phone number:");
    if (phone == null || phone.trim().isEmpty()) return;

    // Step 2: Ask for amount
    String amountStr = JOptionPane.showInputDialog(this, "Enter amount to pay (UGX):");
    if (amountStr == null || amountStr.trim().isEmpty()) return;

    int amount;
    try {
        amount = Integer.parseInt(amountStr);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Invalid amount format.");
        return;
    }
   // Step 3: Choose payment method
    String[] options = {"Airtel Pay", "MoMo Pay", "PayPal"};
    String choice = (String) JOptionPane.showInputDialog(this, "Choose payment method:", "Payment",
            JOptionPane.PLAIN_MESSAGE, null, options, options[0]);

    if (choice == null) return;

    // Step 4: Call the correct method
    
switch (choice) {
    case "Airtel Pay":
        PaymentMethods.initiateAirtelPayment(phone, amount);
        break;
    case "MoMo Pay":
        PaymentMethods.initiateMoMoPayment(phone, amount);
        break;
    case "PayPal":
        PaymentMethods.redirectToPayPal(phone, amount); // using phone as email for now
        break;
}
String receipt = String.format(
    "✅ Payment Successful!\n\nMethod: %s\nPhone: %s\nAmount: UGX %,d\n\nThank you for using our service.",
    choice, phone, amount
);
JOptionPane.showMessageDialog(this, receipt, "Payment Receipt", JOptionPane.INFORMATION_MESSAGE);



    }//GEN-LAST:event_jButtonMakePaymentsActionPerformed

    private void jMenuItemLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLogOutActionPerformed
        // TODO add your handling code here:
        Login login = new Login();
    login.setVisible(true);
    this.dispose(); // close the dashboard

    }//GEN-LAST:event_jMenuItemLogOutActionPerformed

    private void jButtonClearCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearCartActionPerformed
        // TODO add your handling code here:
        clearCart();

    }//GEN-LAST:event_jButtonClearCartActionPerformed

    private void jMenuItemMyOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMyOrdersActionPerformed
        // TODO add your handling code here:
        
    try (Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/ecommercesystem", "root", "")) {
        PreparedStatement ps = conn.prepareStatement(
            "SELECT order_id, order_date, status FROM orders WHERE user_id = ? ORDER BY order_date DESC"
        );
        ps.setString(1, currentUserId);
        ResultSet rs = ps.executeQuery();

        // Build table model
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(new String[] { "Order ID", "Date", "Status" });

        while (rs.next()) {
            int orderId = rs.getInt("order_id");
            Timestamp date = rs.getTimestamp("order_date");
            String status = rs.getString("status");

            model.addRow(new Object[] { orderId, date, status });
        }

        JTable table = new JTable(model);
        table.setRowHeight(25);
        table.setFont(new java.awt.Font("SansSerif", java.awt.Font.PLAIN, 13));
        table.getTableHeader().setFont(new java.awt.Font("SansSerif", java.awt.Font.BOLD, 14));

        JScrollPane scrollPane = new JScrollPane(table);
        scrollPane.setPreferredSize(new Dimension(500, 300));

        JOptionPane.showMessageDialog(this, scrollPane, "My Orders", JOptionPane.PLAIN_MESSAGE);

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error loading orders.");
    }


    }//GEN-LAST:event_jMenuItemMyOrdersActionPerformed

    private void jButtonTrackShippingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTrackShippingActionPerformed
        // TODO add your handling code here:
        
    String orderId = JOptionPane.showInputDialog(this, "Enter Order ID to track shipping:");
    if (orderId == null || orderId.trim().isEmpty()) return;

    try (Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/ecommercesystem", "root", "");
         PreparedStatement stmt = conn.prepareStatement(
             "SELECT address, city, country, shipped_date, delivery_date FROM shipping WHERE order_id = ?")) {

        stmt.setInt(1, Integer.parseInt(orderId));
        ResultSet rs = stmt.executeQuery();

        if (rs.next()) {
            String address = rs.getString("address");
            String city = rs.getString("city");
            String country = rs.getString("country");
            Timestamp shipDate = rs.getTimestamp("shipped_date");
            Timestamp deliveryDate = rs.getTimestamp("delivery_date");

            String message = String.format(
                "Shipping Info:\nAddress: %s\nCity: %s\nCountry: %s\nShipped: %s\nDelivery: %s",
                address, city, country,
                shipDate != null ? shipDate.toString() : "Not yet shipped",
                deliveryDate != null ? deliveryDate.toString() : "Not yet delivered"
            );

            JOptionPane.showMessageDialog(this, message);
        } else {
            JOptionPane.showMessageDialog(this, "No shipping info found for Order ID: " + orderId);
        }

    } catch (SQLException | NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }


    }//GEN-LAST:event_jButtonTrackShippingActionPerformed

    private void jMenuItemTrackShippingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTrackShippingActionPerformed
        // TODO add your handling code here:
        
    String orderId = JOptionPane.showInputDialog(this, "Enter Order ID to track shipping:");
    if (orderId == null || orderId.trim().isEmpty()) return;

    try (Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/ecommercesystem", "root", "");
         PreparedStatement stmt = conn.prepareStatement(
             "SELECT address, city, country, shipped_date, delivery_date FROM shipping WHERE order_id = ?")) {

        stmt.setInt(1, Integer.parseInt(orderId));
        ResultSet rs = stmt.executeQuery();

        if (rs.next()) {
            String address = rs.getString("address");
            String city = rs.getString("city");
            String country = rs.getString("country");
            Timestamp shipDate = rs.getTimestamp("shipped_date");
            Timestamp deliveryDate = rs.getTimestamp("delivery_date");

            String message = String.format(
                "Shipping Info:\nAddress: %s\nCity: %s\nCountry: %s\nShipped: %s\nDelivery: %s",
                address, city, country,
                shipDate != null ? shipDate.toString() : "Not yet shipped",
                deliveryDate != null ? deliveryDate.toString() : "Not yet delivered"
            );

            JOptionPane.showMessageDialog(this, message);
        } else {
            JOptionPane.showMessageDialog(this, "No shipping info found for Order ID: " + orderId);
        }

    } catch (SQLException | NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }


    }//GEN-LAST:event_jMenuItemTrackShippingActionPerformed

    private void jMenuItemPaymentHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPaymentHistoryActionPerformed
        // TODO add your handling code here:
        jMenuItemPaymentHistory.addActionListener(e -> {
    try {
        String userId = currentUserId; // You already have this from login
        List<String> payments = fetchPaymentsHistory(userId);
        if (payments.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No payment history found.", "Payments History", JOptionPane.INFORMATION_MESSAGE);
        } else {
            StringBuilder message = new StringBuilder("Your Payments:\n\n");
            for (String payment : payments) {
                message.append(payment).append("\n----------------------\n");
            }
            JOptionPane.showMessageDialog(null, message.toString(), "Payments History", JOptionPane.INFORMATION_MESSAGE);
        }
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(null, "Error loading payments: " + ex.getMessage());
    }
});

    }//GEN-LAST:event_jMenuItemPaymentHistoryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }


    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrollPane;
    private javax.swing.JButton btnSearchProducts;
    private javax.swing.JTable cartTable;
    private javax.swing.JButton jButtonAddToCart;
    private javax.swing.JButton jButtonClearCart;
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JButton jButtonMakePayments;
    private javax.swing.JButton jButtonOrderHistory;
    private javax.swing.JButton jButtonPlaceOrder;
    private javax.swing.JButton jButtonTrackShipping;
    private javax.swing.JButton jButtonViewCart;
    private javax.swing.JLabel jLabelCustomerDashboard;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenuAccount;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItemBrowseProducts;
    private javax.swing.JMenuItem jMenuItemEditProfile;
    private javax.swing.JMenuItem jMenuItemLogOut;
    private javax.swing.JMenuItem jMenuItemMyOrders;
    private javax.swing.JMenuItem jMenuItemPaymentHistory;
    private javax.swing.JMenuItem jMenuItemSearchbyCategory;
    private javax.swing.JMenuItem jMenuItemTrackShipping;
    private javax.swing.JMenu jMenuOrders;
    private javax.swing.JMenu jMenuPayments;
    private javax.swing.JMenu jMenushop;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable productTable;
    // End of variables declaration//GEN-END:variables

    
private void loadCartItems() {
    DefaultTableModel model = (DefaultTableModel) cartTable.getModel();
    model.setRowCount(0); // clear existing rows

    try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con = DriverManager.getConnection(dblink, user, password);

        String sql = "SELECT p.product_id, p.name, p.price, c.quantity " +
                     "FROM cart c JOIN products p ON c.product_id = p.product_id " +
                     "WHERE c.user_id = ?";
        PreparedStatement pst = con.prepareStatement(sql);
        pst.setString(1, currentUserId);

        ResultSet rs = pst.executeQuery();
        while (rs.next()) {
            String productId = rs.getString("product_id");
            String name = rs.getString("name");
            double price = rs.getDouble("price");
            int quantity = rs.getInt("quantity");

            model.addRow(new Object[]{productId, name, price, quantity});
        }

        rs.close();
        pst.close();
        con.close();
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error loading cart items.");
    }
}

private void clearCart() {
    try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con = DriverManager.getConnection(dblink, user, password);
        String sql = "DELETE FROM cart WHERE user_id = ?";
        PreparedStatement pst = con.prepareStatement(sql);
        pst.setString(1, currentUserId);

        int rowsDeleted = pst.executeUpdate();
        if (rowsDeleted > 0) {
            JOptionPane.showMessageDialog(null, "Cart cleared successfully.");
        } else {
            JOptionPane.showMessageDialog(null, "Your cart was already empty.");
        }

        pst.close();
        con.close();

        // Refresh the cart table to show it's empty
        loadCartItems();

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error clearing cart.");
    }
}

private int getStock(Connection conn, int productId) throws SQLException {
    PreparedStatement ps = conn.prepareStatement("SELECT stock_quantity FROM products WHERE product_id = ?");
    ps.setInt(1, productId);
    ResultSet rs = ps.executeQuery();
    return rs.next() ? rs.getInt("stock_quantity") : 0;
}

private void updateStock(Connection conn, int productId, int newStock) throws SQLException {
    PreparedStatement ps = conn.prepareStatement("UPDATE products SET stock_quantity = ? WHERE product_id = ?");
    ps.setInt(1, newStock);
    ps.setInt(2, productId);
    ps.executeUpdate();
}

private void insertOrder(Connection conn, String userId) throws SQLException {
    PreparedStatement ps = conn.prepareStatement("INSERT INTO orders (user_id, order_date, status) VALUES (?, NOW(), 'pending')");
    ps.setString(1, userId);
    ps.executeUpdate();
}


private List<String> fetchPaymentsHistory(String userId) throws SQLException {
    List<String> payments = new ArrayList<>();
    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/ecommercesystem", "root", "");

    // Join orders and payments to match user_id
    String query = "SELECT p.payment_id, p.order_id, p.amount, p.payment_date, p.method, p.status " +
                   "FROM payment p JOIN orders o ON p.order_id = o.order_id " +
                   "WHERE o.user_id = ? ORDER BY p.payment_date DESC";

    PreparedStatement ps = conn.prepareStatement(query);
    ps.setString(1, userId);
    ResultSet rs = ps.executeQuery();

    while (rs.next()) {
        String payment = "Payment ID: " + rs.getInt("payment_id") +
                         "\nOrder ID: " + rs.getInt("order_id") +
                         "\nAmount: $" + rs.getDouble("amount") +
                         "\nDate: " + rs.getTimestamp("payment_date") +
                         "\nMethod: " + rs.getString("method") +
                         "\nStatus: " + rs.getString("status");
        payments.add(payment);
    }

    conn.close();
    return payments;
}

}

