/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.awt.Color;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.sql.PreparedStatement;
import javax.swing.*;
import java.sql.*;
import java.awt.*;



/**
 *
 * @author HP
 */
public class SignUp extends javax.swing.JFrame {
    Connection con;
    Statement st;
    String dblink;
    
    String user;
    String Password;
    
    String query;
    ResultSet rs;
     String newID;
     
    
//private JTextField userIdField, TxtfullName, txtphone, TxtEmail;
//private JPasswordField TxtPassword, TxtConfirmPassword;
//private JButton btnSignUp;

    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SignUp.class.getName());

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        con=null;
        st=null;
        dblink="jdbc:mysql://localhost:3306/ecommercesystem";
        user = "root";
        Password = "";
        initComponents();
        getContentPane().setBackground(new Color(255, 182, 193)); // Light pink

        setTitle("Log In");
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
       // ComboBoxRole = new JComboBox<>(new String[] {"admin", "customer", "staff"});
//txtUserId = new JTextField();
//TxtFullName = new JTextField();
//txtphone = new JTextField();
//TxtEmail = new JTextField();
//TxtPassword = new JPasswordField();
//TxtConfirmPassword = new JPasswordField();
////btnSignUp = new JButton("Sign Up");
//
//// Add components to your layout (GridLayout, GroupLayout, etc.)
////add(ComboBoxRole);
//add(lblUserId);
//// ... and so on
//add(btnSignUp);
//ComboBoxRole.addItem(" ");
//ComboBoxRole.addItem("admin");
//ComboBoxRole.addItem("customer");
//ComboBoxRole.addItem("staff");



    




    
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSignUP = new javax.swing.JLabel();
        lblFullName = new javax.swing.JLabel();
        TxtFullName = new javax.swing.JTextField();
        lblphone = new javax.swing.JLabel();
        txtphone = new javax.swing.JTextField();
        LblEmail = new javax.swing.JLabel();
        TxtEmail = new javax.swing.JTextField();
        LblPassword = new javax.swing.JLabel();
        lblconfirmpassword = new javax.swing.JLabel();
        TxtPassword = new javax.swing.JPasswordField();
        TxtConfirmPassword = new javax.swing.JPasswordField();
        btnSignUp = new javax.swing.JButton();
        lblrole = new javax.swing.JLabel();
        ComboBoxRole = new javax.swing.JComboBox<>();
        lblUserId = new javax.swing.JLabel();
        txtUserId = new javax.swing.JTextField();
        jButtonCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblSignUP.setText("            Sign Up");

        lblFullName.setText("Full Name");

        lblphone.setText("Phone");

        LblEmail.setText("Email");

        LblPassword.setText("Password");

        lblconfirmpassword.setText("Confirm Password");

        TxtConfirmPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtConfirmPasswordActionPerformed(evt);
            }
        });

        btnSignUp.setText("Sign Up");
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });

        lblrole.setText("Role");

        ComboBoxRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "customer", "admin", "staff" }));
        ComboBoxRole.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboBoxRoleItemStateChanged(evt);
            }
        });
        ComboBoxRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxRoleActionPerformed(evt);
            }
        });

        lblUserId.setText("UserId");

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblEmail)
                            .addComponent(LblPassword)
                            .addComponent(lblconfirmpassword))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblphone)
                            .addComponent(lblUserId)
                            .addComponent(lblFullName))
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtUserId)
                                .addGap(23, 23, 23))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TxtFullName, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtphone, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblrole)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(115, 115, 115)
                                .addComponent(ComboBoxRole, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addComponent(lblSignUP, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))))
            .addGroup(layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(btnSignUp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonCancel)
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSignUP, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblrole)
                    .addComponent(ComboBoxRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserId)
                    .addComponent(txtUserId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFullName)
                    .addComponent(TxtFullName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblphone)
                    .addComponent(txtphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblEmail)
                    .addComponent(TxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblPassword)
                    .addComponent(TxtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblconfirmpassword)
                    .addComponent(TxtConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSignUp)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonCancel)
                        .addGap(14, 14, 14))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtConfirmPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtConfirmPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtConfirmPasswordActionPerformed

    private void ComboBoxRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxRoleActionPerformed
        // TODO add your handling code here:
        //VAriables to help with Automatic IDs
        String currentID, numberPart;
        int newNumber;
        
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            con=DriverManager.getConnection(dblink, user, Password); //Creating the connection
            st=con.createStatement(); //Creating the statement
            switch (ComboBoxRole.getSelectedItem().toString()) {
                case "customer":
                    query="select user_id from users where role='customer' order by user_id desc limit 1";
                    rs=st.executeQuery(query);
                    if(rs.next()){
                        currentID = rs.getString("user_id"); //Current ID from the database
                        
                        numberPart = currentID.substring(1); // Removing the letter part of the ID
                        
                        newNumber = Integer.parseInt(numberPart) + 1; //Adding 1 to the numberPart
                        
                        newID = "C" + String.format("%02d", newNumber);
                    }else{
                        newID = "C01"; // Giving a default ID of C01
                    }   break;
                case "admin":
                    query="select user_id from users where role='admin' order by user_id desc limit 1";
                    rs=st.executeQuery(query);
                    if(rs.next()){
                        currentID = rs.getString("user_id"); //Current ID from the database
                        
                        numberPart = currentID.substring(1); // Removing the letter part of the ID
                        
                        newNumber = Integer.parseInt(numberPart) + 1; //Adding 1 to the numberPart
                        
                        newID = "A" + String.format("%02d", newNumber);
                    }else{
                        newID = "A01"; // Giving a default ID of A01
                    }   break;
                case "staff":
                    query="select user_id from users where role='staff' order by user_id desc limit 1";
                    rs=st.executeQuery(query);
                    if(rs.next()){
                        currentID = rs.getString("user_id"); //Current ID from the database
                        
                        numberPart = currentID.substring(1); // Removing the letter part of the ID
                        
                        newNumber = Integer.parseInt(numberPart) + 1; //Adding 1 to the numberPart
                        
                        newID = "S" + String.format("%02d", newNumber);
                    }else{
                        newID = "S01"; // Giving a default ID of S01
                    }   break;
                default:
                    break;
            }
            
            txtUserId.setText(newID);
        }
        catch(SQLException ex){
            ex.printStackTrace();
        }
        catch(ClassNotFoundException e){
            e.printStackTrace();
        }
        finally{
            try{
                if (st != null){st.close();}
                if (con != null){con.close();}
                if (rs != null){rs.close();}
            }
            catch (SQLException ex){
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_ComboBoxRoleActionPerformed

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        // TODO add your handling code here:
       
        String role = ComboBoxRole.getSelectedItem().toString();
        String user_id = txtUserId.getText().trim();
        String full_name = TxtFullName.getText().trim();
        String phone = txtphone.getText().trim();
        String email = TxtEmail.getText().trim();
        String password = new String(TxtPassword.getPassword());
        String confirmPassword = new String(TxtConfirmPassword.getPassword());

        // Basic validation
        if (user_id.equals(" ") || full_name.equals(" ") || phone.equals(" ") || email.equals(" ") || password.equals(" ")) {
            JOptionPane.showMessageDialog(null, "Please fill in all fields.");
            return;
        }

        else if (!password.equals(confirmPassword)) {
            JOptionPane.showMessageDialog(null, "Passwords do not match.");
            return;
        }

        try (Connection conn = DriverManager.getConnection(dblink, user, Password)) {
            String sql = "INSERT INTO Users (role, user_id, full_name, phone, email, password) VALUES (?, ?, ?, ?, ?, ?)";
            

            PreparedStatement stmt = conn.prepareStatement(sql);
            stmt.setString(1, role);
            stmt.setString(2, user_id);
            stmt.setString(3, full_name);
            stmt.setString(4, phone);
            stmt.setString(5, email);
            stmt.setString(6, password); // Consider hashing this!

            int rowsInserted = stmt.executeUpdate();
            if (rowsInserted > 0) {
                JOptionPane.showMessageDialog(null, "Registration successful!");
                dispose(); // Close SignUp frame
                new Login().setVisible(true); // Return to login
            } else {
                JOptionPane.showMessageDialog(null, "Registration failed. Try again.");
            }

        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Database error: " + ex.getMessage());
        }
    
    

    }//GEN-LAST:event_btnSignUpActionPerformed

    private void ComboBoxRoleItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboBoxRoleItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxRoleItemStateChanged

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        // TODO add your handling code here:
         this.dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void Main(){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SignUp().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxRole;
    private javax.swing.JLabel LblEmail;
    private javax.swing.JLabel LblPassword;
    private javax.swing.JPasswordField TxtConfirmPassword;
    private javax.swing.JTextField TxtEmail;
    private javax.swing.JTextField TxtFullName;
    private javax.swing.JPasswordField TxtPassword;
    private javax.swing.JButton btnSignUp;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JLabel lblFullName;
    private javax.swing.JLabel lblSignUP;
    private javax.swing.JLabel lblUserId;
    private javax.swing.JLabel lblconfirmpassword;
    private javax.swing.JLabel lblphone;
    private javax.swing.JLabel lblrole;
    private javax.swing.JTextField txtUserId;
    private javax.swing.JTextField txtphone;
    // End of variables declaration//GEN-END:variables
}
