
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.util.List;
import java.util.ArrayList;
import java.sql.Timestamp;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author HP
 */
public class StaffMenu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(StaffMenu.class.getName());

    /**
     * Creates new form StaffMenu
     */
    public StaffMenu() {
        initComponents();
        getContentPane().setBackground(new Color(255, 182, 193)); // Light pink

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jLabelStaffDashboard = new javax.swing.JLabel();
        jButtonAddNewProduct = new javax.swing.JButton();
        jButtonUpdateStock = new javax.swing.JButton();
        jButtonEditProductInfo = new javax.swing.JButton();
        jButtonViewOrders = new javax.swing.JButton();
        jButtonUpdateShippingStatus = new javax.swing.JButton();
        jButtonGenerateReport = new javax.swing.JButton();
        jButtonLogout = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuOrders = new javax.swing.JMenu();
        jMenuItemViewOrders = new javax.swing.JMenuItem();
        jMenuItemManageShipping = new javax.swing.JMenuItem();
        jMenuReports = new javax.swing.JMenu();
        jMenuItemDailySales = new javax.swing.JMenuItem();
        jMenuItemInventoryStatus = new javax.swing.JMenuItem();
        jMenuAccount = new javax.swing.JMenu();
        jMenuItemLogOut = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelStaffDashboard.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelStaffDashboard.setForeground(new java.awt.Color(183, 110, 121));
        jLabelStaffDashboard.setText("         Staff Dashboard");
        getContentPane().add(jLabelStaffDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 19, 151, 34));

        jButtonAddNewProduct.setText("Add New Product");
        jButtonAddNewProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddNewProductActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAddNewProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 96, 160, -1));

        jButtonUpdateStock.setText("Update Stock");
        jButtonUpdateStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateStockActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonUpdateStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 96, 149, -1));

        jButtonEditProductInfo.setText("Edit Product Info");
        jButtonEditProductInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditProductInfoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEditProductInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 131, 160, -1));

        jButtonViewOrders.setText("View Orders");
        jButtonViewOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewOrdersActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonViewOrders, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 131, 149, -1));

        jButtonUpdateShippingStatus.setText("Update Shipping Status");
        jButtonUpdateShippingStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateShippingStatusActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonUpdateShippingStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 172, 160, -1));

        jButtonGenerateReport.setText("Generate Report");
        getContentPane().add(jButtonGenerateReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 172, 149, -1));

        jButtonLogout.setText("Logout");
        jButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 149, -1));

        jMenuOrders.setText("Orders");

        jMenuItemViewOrders.setText("View Orders");
        jMenuOrders.add(jMenuItemViewOrders);

        jMenuItemManageShipping.setText("Manage Shipping");
        jMenuItemManageShipping.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemManageShippingActionPerformed(evt);
            }
        });
        jMenuOrders.add(jMenuItemManageShipping);

        jMenuBar1.add(jMenuOrders);

        jMenuReports.setText("Reports");

        jMenuItemDailySales.setText("Daily Sales");
        jMenuReports.add(jMenuItemDailySales);

        jMenuItemInventoryStatus.setText("Inventory Status");
        jMenuReports.add(jMenuItemInventoryStatus);

        jMenuBar1.add(jMenuReports);

        jMenuAccount.setText("Account");

        jMenuItemLogOut.setText("Logout");
        jMenuAccount.add(jMenuItemLogOut);

        jMenuBar1.add(jMenuAccount);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonUpdateStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateStockActionPerformed
        // TODO add your handling code here:
        jButtonUpdateStock.addActionListener(e -> {
    try {
        String productIdStr = JOptionPane.showInputDialog(null, "Enter Product ID to update stock:");
        String newStockStr = JOptionPane.showInputDialog(null, "Enter new stock quantity:");

        if (productIdStr != null && newStockStr != null) {
            int productId = Integer.parseInt(productIdStr);
            int newStock = Integer.parseInt(newStockStr);
            boolean success = updateProductStock(productId, newStock);
            if (success) {
                JOptionPane.showMessageDialog(null, "Stock updated.");
            } else {
                JOptionPane.showMessageDialog(null, "Update failed. Product ID may not exist.");
            }
        }
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
    }
});

    }//GEN-LAST:event_jButtonUpdateStockActionPerformed

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed
        // TODO add your handling code here:
        Login login = new Login();
    login.setVisible(true);
    this.dispose(); // close the dashboard

    }//GEN-LAST:event_jButtonLogoutActionPerformed

    private void jButtonViewOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewOrdersActionPerformed
        // TODO add your handling code here:
        jButtonViewOrders.addActionListener(e -> {
    try {
        List<String> orders = fetchAllOrders(); // method defined below
        StringBuilder message = new StringBuilder("Orders:\n\n");
        for (String order : orders) {
            message.append(order).append("\n----------------------\n");
        }
        JOptionPane.showMessageDialog(null, message.toString(), "All Orders", JOptionPane.INFORMATION_MESSAGE);
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(null, "Error loading orders: " + ex.getMessage());
    }
});

    }//GEN-LAST:event_jButtonViewOrdersActionPerformed

    private void jButtonUpdateShippingStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateShippingStatusActionPerformed
        // TODO add your handling code here:
        jButtonUpdateShippingStatus.addActionListener(e -> {
    try {
        String orderIdStr = JOptionPane.showInputDialog(null, "Enter Order ID to update:");
        if (orderIdStr != null && !orderIdStr.isEmpty()) {
            int orderId = Integer.parseInt(orderIdStr);

            String[] options = {"pending", "shipped", "delivered", "cancelled"};
            String newStatus = (String) JOptionPane.showInputDialog(
                null,
                "Select new status for Order ID " + orderId,
                "Update Shipping Status",
                JOptionPane.QUESTION_MESSAGE,
                null,
                options,
                options[0]
            );

            if (newStatus != null) {
                boolean success = updateOrderStatus(orderId, newStatus); // method defined below
                if (success) {
                    JOptionPane.showMessageDialog(null, "Status updated to " + newStatus);
                } else {
                    JOptionPane.showMessageDialog(null, "Update failed. Order ID may not exist.");
                }
            }
        }
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
    }
});

    }//GEN-LAST:event_jButtonUpdateShippingStatusActionPerformed

    private void jButtonAddNewProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddNewProductActionPerformed
        // TODO add your handling code here:
        jButtonAddNewProduct.addActionListener(e -> {
    try {
        String name = JOptionPane.showInputDialog(null, "Enter product name:");
        String description = JOptionPane.showInputDialog(null, "Enter product description:");
        String priceStr = JOptionPane.showInputDialog(null, "Enter product price:");
        String stockStr = JOptionPane.showInputDialog(null, "Enter stock quantity:");

        if (name != null && priceStr != null && stockStr != null) {
            double price = Double.parseDouble(priceStr);
            int stock = Integer.parseInt(stockStr);
            boolean success = insertNewProduct(name, description, price, stock);
            if (success) {
                JOptionPane.showMessageDialog(null, "Product added successfully.");
            } else {
                JOptionPane.showMessageDialog(null, "Failed to add product.");
            }
        }
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
    }
});

    }//GEN-LAST:event_jButtonAddNewProductActionPerformed

    private void jButtonEditProductInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditProductInfoActionPerformed
        // TODO add your handling code here:
        jButtonEditProductInfo.addActionListener(e -> {
    try {
        String productIdStr = JOptionPane.showInputDialog(null, "Enter Product ID to edit:");
        if (productIdStr != null && !productIdStr.isEmpty()) {
            int productId = Integer.parseInt(productIdStr);
            String newName = JOptionPane.showInputDialog(null, "Enter new product name:");
            String newDescription = JOptionPane.showInputDialog(null, "Enter new description:");
            String newPriceStr = JOptionPane.showInputDialog(null, "Enter new price:");

            if (newName != null && newPriceStr != null) {
                double newPrice = Double.parseDouble(newPriceStr);
                boolean success = updateProductInfo(productId, newName, newDescription, newPrice);
                if (success) {
                    JOptionPane.showMessageDialog(null, "Product info updated.");
                } else {
                    JOptionPane.showMessageDialog(null, "Update failed. Product ID may not exist.");
                }
            }
        }
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
    }
});

    }//GEN-LAST:event_jButtonEditProductInfoActionPerformed

    private void jMenuItemManageShippingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemManageShippingActionPerformed
        // TODO add your handling code here:
        jMenuItemManageShipping.addActionListener(e -> {
    try {
        String orderIdStr = JOptionPane.showInputDialog(null, "Enter Order ID to manage shipping:");
        if (orderIdStr != null && !orderIdStr.isEmpty()) {
            int orderId = Integer.parseInt(orderIdStr);

            String[] options = {"View Shipping Info", "Edit Shipping Info", "Mark as Shipped"};
            String choice = (String) JOptionPane.showInputDialog(
                null,
                "Choose an action for Order ID " + orderId,
                "Manage Shipping",
                JOptionPane.QUESTION_MESSAGE,
                null,
                options,
                options[0]
            );

            if ("View Shipping Info".equals(choice)) {
                viewShippingInfo(orderId);
            } else if ("Edit Shipping Info".equals(choice)) {
                editShippingInfo(orderId);
            } else if ("Mark as Shipped".equals(choice)) {
                markOrderAsShipped(orderId);
            }
        }
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
    }
});

    }//GEN-LAST:event_jMenuItemManageShippingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new StaffMenu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddNewProduct;
    private javax.swing.JButton jButtonEditProductInfo;
    private javax.swing.JButton jButtonGenerateReport;
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JButton jButtonUpdateShippingStatus;
    private javax.swing.JButton jButtonUpdateStock;
    private javax.swing.JButton jButtonViewOrders;
    private javax.swing.JLabel jLabelStaffDashboard;
    private javax.swing.JMenu jMenuAccount;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItemDailySales;
    private javax.swing.JMenuItem jMenuItemInventoryStatus;
    private javax.swing.JMenuItem jMenuItemLogOut;
    private javax.swing.JMenuItem jMenuItemManageShipping;
    private javax.swing.JMenuItem jMenuItemViewOrders;
    private javax.swing.JMenu jMenuOrders;
    private javax.swing.JMenu jMenuReports;
    // End of variables declaration//GEN-END:variables

private List<String> fetchAllOrders() throws SQLException {
    List<String> orders = new ArrayList<>();
    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/ecommercesystem", "root", "");
    String query = "SELECT order_id, user_id, order_date, status FROM orders ORDER BY order_date DESC";
    PreparedStatement ps = conn.prepareStatement(query);
    ResultSet rs = ps.executeQuery();
    while (rs.next()) {
        String order = "Order ID: " + rs.getInt("order_id") +
                       "\nUser ID: " + rs.getString("user_id") +
                       "\nDate: " + rs.getTimestamp("order_date") +
                       "\nStatus: " + rs.getString("status");
        orders.add(order);
    }
    conn.close();
    return orders;
}

private boolean updateOrderStatus(int orderId, String newStatus) throws SQLException {
    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/ecommercesystem", "root", "");
    String query = "UPDATE orders SET status = ? WHERE order_id = ?";
    PreparedStatement ps = conn.prepareStatement(query);
    ps.setString(1, newStatus);
    ps.setInt(2, orderId);
    int rows = ps.executeUpdate();
    conn.close();
    return rows > 0;
}

private boolean insertNewProduct(String name, String description, double price, int stock) throws SQLException {
    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/ecommercesystem", "root", "");
    String query = "INSERT INTO products (name, description, price, stock_quantity) VALUES (?, ?, ?, ?)";
    PreparedStatement ps = conn.prepareStatement(query);
    ps.setString(1, name);
    ps.setString(2, description);
    ps.setDouble(3, price);
    ps.setInt(4, stock);
    int rows = ps.executeUpdate();
    conn.close();
    return rows > 0;
}
private boolean updateProductInfo(int productId, String name, String description, double price) throws SQLException {
    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/ecommercesystem", "root", "");
    String query = "UPDATE products SET name = ?, description = ?, price = ? WHERE product_id = ?";
    PreparedStatement ps = conn.prepareStatement(query);
    ps.setString(1, name);
    ps.setString(2, description);
    ps.setDouble(3, price);
    ps.setInt(4, productId);
    int rows = ps.executeUpdate();
    conn.close();
    return rows > 0;
}

private boolean updateProductStock(int productId, int newStock) throws SQLException {
    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/ecommercesystem", "root", "");
    String query = "UPDATE products SET stock_quantity = ? WHERE product_id = ?";
    PreparedStatement ps = conn.prepareStatement(query);
    ps.setInt(1, newStock);
    ps.setInt(2, productId);
    int rows = ps.executeUpdate();
    conn.close();
    return rows > 0;
}
private void viewShippingInfo(int orderId) throws SQLException {
    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/ecommercesystem", "root", "");
    String query = "SELECT * FROM shipping WHERE order_id = ?";
    PreparedStatement ps = conn.prepareStatement(query);
    ps.setInt(1, orderId);
    ResultSet rs = ps.executeQuery();
    if (rs.next()) {
        String info = "Shipping ID: " + rs.getInt("shipping_id") +
                      "\nAddress: " + rs.getString("address") +
                      "\nCity: " + rs.getString("city") +
                      "\nPostal Code: " + rs.getString("postal_code") +
                      "\nCountry: " + rs.getString("country") +
                      "\nDate Shipped: " + rs.getTimestamp("date_shipped");
        JOptionPane.showMessageDialog(null, info, "Shipping Info", JOptionPane.INFORMATION_MESSAGE);
    } else {
        JOptionPane.showMessageDialog(null, "No shipping info found for this order.");
    }
    conn.close();
}

private void editShippingInfo(int orderId) throws SQLException {
    String address = JOptionPane.showInputDialog(null, "Enter address:");
    String city = JOptionPane.showInputDialog(null, "Enter city:");
    String postal = JOptionPane.showInputDialog(null, "Enter postal code:");
    String country = JOptionPane.showInputDialog(null, "Enter country:");

    if (address != null && city != null && postal != null && country != null) {
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/ecommercesystem", "root", "");

        // Check if shipping record exists
        String checkQuery = "SELECT shipping_id FROM shipping WHERE order_id = ?";
        PreparedStatement checkPs = conn.prepareStatement(checkQuery);
        checkPs.setInt(1, orderId);
        ResultSet rs = checkPs.executeQuery();

        if (rs.next()) {
            // Update existing record
            String updateQuery = "UPDATE shipping SET address = ?, city = ?, postal_code = ?, country = ? WHERE order_id = ?";
            PreparedStatement ps = conn.prepareStatement(updateQuery);
            ps.setString(1, address);
            ps.setString(2, city);
            ps.setString(3, postal);
            ps.setString(4, country);
            ps.setInt(5, orderId);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Shipping info updated.");
        } else {
            // Insert new record
            String insertQuery = "INSERT INTO shipping (order_id, address, city, postal_code, country) VALUES (?, ?, ?, ?, ?)";
            PreparedStatement ps = conn.prepareStatement(insertQuery);
            ps.setInt(1, orderId);
            ps.setString(2, address);
            ps.setString(3, city);
            ps.setString(4, postal);
            ps.setString(5, country);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Shipping info added.");
        }

        conn.close();
    }
}

private void markOrderAsShipped(int orderId) throws SQLException {
    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/ecommercesystem", "root", "");

    // Update orders table
    String updateOrder = "UPDATE orders SET status = 'shipped' WHERE order_id = ?";
    PreparedStatement ps1 = conn.prepareStatement(updateOrder);
    ps1.setInt(1, orderId);
    ps1.executeUpdate();

    // Update shipping table
    String updateShipping = "UPDATE shipping SET date_shipped = NOW() WHERE order_id = ?";
    PreparedStatement ps2 = conn.prepareStatement(updateShipping);
    ps2.setInt(1, orderId);
    ps2.executeUpdate();

    conn.close();
    JOptionPane.showMessageDialog(null, "Order marked as shipped.");
}


}

